[package]
name = "flecs"
version = "0.1.0"
edition = "2018"

[profile.release]
debug = true

[dependencies]
lazy_static = "1.4.0"

[build-dependencies]
bindgen = "0.59.1"
cc = "1.0.70"

[[example]]
name="dynamic_components"
test = true

[[example]]
name="filters"
test = true

[[example]]
name="systems"
test = true